# Arquivo de exemplo para configuração do sistema
# Copie este arquivo para config/config.yaml e preencha os valores corretos
# -----------------------------------------------------

smtp:
  host: smtp.exemplo.com.br  # Servidor SMTP para envio de emails
  port: 587                  # Porta do servidor SMTP
  use_tls: true              # Usar TLS para conexão segura
  retry_attempts: 3          # Número de tentativas em caso de falha
  retry_delay: 5             # Tempo entre tentativas (segundos)
  send_timeout: 5            # Timeout para envio (segundos)

email:
  sender: "Seu Nome | Sua Empresa <seu@email.com>"  # Nome e email do remetente
  batch_size: 200            # Quantidade de emails por lote
  batch_delay: 30            # Tempo entre lotes (segundos)
  csv_file: data/emails_geral.csv             # Arquivo principal de emails
  unsubscribe_file: data/descadastros.csv     # Arquivo de emails descadastrados
  test_recipient: test@example.com            # Email para testes individuais
  test_emails_file: data/test_emails.csv      # Arquivo de emails para testes em lote 